export const ROUTES = {
    HOME: "/",
    LOGIN: "/login",
    LOGOUT: "/logout",
    ACCOUNT_SETTING: "/account-setting",
    FORGOT_PASSWORD: "/forgot-password",
    CONFIRM_OTP: "/confirm-otp",
    CHANGE_PASSWORD: "/change-password",
    SIGN_UP: "/sign-up",
    CHALLENGE: "/challenge",
    CHALLENGE_DETAIL: "/challenge/detail",
    RECIPE: "/recipe",
    SAVE_FOOD: "/save-food",
    SEARCH: "/search",
    ARTICLE_POST: "/article-post",
    ARTICLE_UPDATE: "/article-update",
};
